---
title: "Inspection Summary of Chinese Restaurants in New York City"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r, include = FALSE}
data("rest_inspec")

chinese_rest = 
  rest_inspec %>% 
  filter(
    grade %in% c("A", "B", "C"), 
    boro != "Missing",
    cuisine_description == "Chinese") %>% 
  mutate(boro = str_to_title(boro)) %>% 
  select(boro, dba, score, grade, grade_date) %>% 
  distinct()
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r scatterplot}
chinese_rest %>% 
  group_by(boro, grade_date) %>% 
  summarize(mean_score = mean(score)) %>% 
  plot_ly(
    x = ~grade_date, y = ~mean_score, color = ~boro,
    type = "scatter", mode = "lines", colors = "viridis") %>% 
  layout(
    title = "Mean Violation Scores of Chinese Restaurants in New York City
    (Mar 2013 - Oct 2017)",
    xaxis = list(title = "Inspection Date"),
    yaxis = list(title = "Mean Violation Score"))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r boxplot}
chinese_rest %>% 
  separate(col = grade_date, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  filter(year == "2017", score < 30) %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis") %>% 
  layout(
    title = "Violation Score of Chinese Restaurants 
    in New York City, 2017",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Violations Score"))
```

### Chart C

```{r bar plot}
chinese_rest %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = grade, values_from = n) %>% 
  plot_ly(x = ~boro, y = ~A, type = "bar", name = "A") %>% 
  add_trace(y = ~B, name = "B") %>% 
  add_trace(y = ~C, name = "C") %>% 
  layout(
    title = "Number and Grade of Violations in Chinese Restaurants in New York City
    (Mar 2013 - Oct 2017)",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Number of Violations"), barmode = "stack")
```


