---
title: "Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Graduate Teaching Assistant, Sep 2022 - Current 

* I am currently a Teaching Assistant for the **Quantitative Research Methods Module** at **Columbia Mailman School of Public Health**

* I lead weekly lab sessions for 17 students to go over practice questions together and host weekly office hours.

* I grade student assignments and respond to inquiries and follow-up in a timely manner

* In addition, I pilot assignments and exams, provide feedback, and maintain regular communication with the lead TAs and faculty


## Practicum Student, Jun 2022 - Current

* I was a practicum student with Dr. Yiwey Shieh at the **Department of Population Health Sciences** at **Weill Cornell Medicine**.

* Our project focused on risk factors for breast cancer and the association between polygenic risk score and interval breast cancer

* I learned how to clean and merge breast cancer patient dataset using R, and analyze data using biostatistical methods such as logistic regression.


## Undergraduate Research Assistant, May 2019 - Aug 2021 

* I started as a co-op student at Dr. Peter Black's lab and continued as a thesis student and an undergraduate Research Assistant at the **Vancouver Prostate Centre**. 

* I designed and conducted molecular biology experiments such as RT-qPCR and Western Blot with precision and proficiency. I learned and matured quickly, from learning everything from scratch to providing technical training for nnew students and post-docs.

* Working with various physicians and post-docs, I facilitated with multiple projects on a range of scope, from maintaining bladder cancer mouse models, conducting wet-lab experiments, to processing patient sample and constructing patient database.

* Together with my supervisor, Dr. Takashi Motsumoto, we drafted a research manuscript. The abstract was presented at the International Bladder Cancer Network 2020 and published in [*Urologic Oncology*](https://doi.org/10.1016/j.urolonc.2020.10.048).